### ISSUE TITLE
Unable to read file header on linux

### ISSUE THREAD

**Issue by dagmarkrefting** [bigsasi/arousals-detection#1]
Hi,
i tried to run the runExample.m on Matlab 2015b. First, the path is given with windows file separator, that was easy to change, however, it would be better to use fullfile, as it adds the the file separators according to the  operating system. 

However, after changing that, I got the following error:

> Error opening the file
> Unable to read file header ../DemoFiles/Male04yrs 04-AUG-2016 20h04m00s PSG_hypnogram.EDF >Attempt to reference field of non-structure array.

**Comment by bigsasi** [comment]
Hi! I believe the problem is the directory from which you are running the example.
I just updated the example so now it finds the demo file in your path (and also uses the right file separator).

Hope it works.

**Comment by dagmarkrefting** [comment]
works now, thanks for the quick fix :-)
